- deploy.sh
Travis need to stage removed files as well. Therefore we need to use --all.
> chore: add removed files to git stage

- deploy.sh
To protect the master branch travis will update pull request branches
after each push, build and commit the changes.
This means pull requests need to be merged by persons responsible for
the website. Travis will not update the master anymore.
> chore: travis updates pull requests

- scripts/deploy-staging.sh
- src/templates/module_40_navigation/styles.less
> fix: adapt mainnav to new layout

- src/templates/module_22_story2/styles.less
> fix: position image absolute to module box

- docs/index.html
Hey there,<br />
This pull requests contains the build changes caused by 34076cb4bedfb0c60205d39c53b454c8a81f44a6.<br/>
When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>
Cheers<br/>
---<br />
**Target**: Production :rotating_light:<br />
**Source**: Commit to master
> Deploy changes for 34076cb

- docs/index.html
Hey there,<br />
This pull requests contains the changes proposed by sinnerschrader/sinnerschrader-website#false.<br/>
When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>
Cheers<br/>
---<br />
**Target**: Production :rotating_light:<br />
**Source**: Pull Request
> Deploy changes for #135

- docs/about/why/index.html
- docs/work/curved/index.html
Hey there,<br />This pull requests contains the build changes caused by c4917034048bfe6511e56adaeb8c6a1495df5874.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for c491703

- docs/about/how/index.html
- docs/about/why/index.html
Hey there,<br />This pull requests contains the build changes caused by c8d95cce3da13c07259216c023be4a183ed104ca.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for c8d95cc

- docs/about/how/index.html
Hey there,<br />This pull requests contains the build changes caused by 745eb59eb66841aad3aea2ea3e9f6c0c082be11e.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for 745eb59

- docs/imprint/index.html
Hey there,<br />This pull requests contains the build changes caused by e527d91f7744ae272e3e955415e7f0018e08ea60.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for e527d91

- docs/about/how/index.html
- docs/about/what/index.html
- docs/about/who/index.html
- docs/about/why/index.html
- docs/contact/index.html
- docs/index.html
- docs/work/curved/index.html
- docs/work/ep-guide/index.html
- docs/work/index.html
- docs/work/maxblue/index.html
- docs/work/raumfeld/index.html
- docs/work/tuifly/index.html
Hey there,<br />This pull requests contains the build changes caused by c039b118466e9fa265f37d08dbd8a033e299d295.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for c039b11

- docs/about/what/index.html
Hey there,<br />This pull requests contains the build changes caused by c42de1eb6cceaa092cff1ab63691d158283abbd5.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for c42de1e

- docs/contact/index.html
- docs/de/agentur/news/ad-hoc-mitteilung/index.html
- docs/de/agentur/news/becks-startet-lieferservice/index.html
- docs/de/agentur/news/dfv-mediengruppe-neuer-partner-der-next-berlin/index.html
- docs/de/agentur/news/die-fantastischen-vier-feiern-25-jubilaeum-mit-sinnerschrader/index.html
- docs/de/agentur/news/next-sd-mit-digitalen-servicestrategien-zum-erfolg/index.html
- docs/de/agentur/news/next-service-design-am-8-oktober-in-berlin/index.html
- docs/de/agentur/news/sinnerschrader-entwickelt-neue-bestellplattform-fuer-joeys-pizza/index.html
- docs/de/agentur/news/sinnerschrader-wachst-im-vierten-quartal-20112012-wieder-zweistellig/index.html
- docs/de/news/anheuser-busch-inbev-vergibt-digital-etat-fuer-becks/index.html
- docs/de/news/bestes-arbeitgeber-image-aller-digitalagenturen/index.html
- docs/de/news/munchener-standort-von-sinnerschrader-wachst/index.html
- docs/de/news/next-berlin-2013-leading-european-digital/index.html
- docs/de/news/nextberlin13-google-glass-und-digitaltrends-zum-anfassen/index.html
- docs/de/news/sinnerschrader-gewinnt-digital-experience-etat-von-unitymedia-kabelbw/index.html
- docs/de/news/sinnerschrader-wachst-in-den-ersten-neun-monaten-20112012-um-18-prozent-anpassung-der-ergebnisprognose-nach-einbusen-bei-spot-media/index.html
- docs/de/news/sinnerschrader-wird-globale-digitalagentur-von-skoda-haasenstein-ubernimmt-kommunikationsaufgaben/index.html
- docs/de/news/sinnerschrader-wird-kreative-leadagentur-von-guardian-industries-europa/index.html
- docs/news/34-wachstum-in-q2/index.html
- docs/news/erste-top-sprecher-heute-verkundet/index.html
- docs/news/next13-start-up-pitch-12-finalisten-stehen-fest/index.html
- docs/news/red-dot-design-award-fur-haasenstein/index.html
- docs/news/sinnerschrader-baut-service-design-weiter-aus/index.html
- docs/news/trendkonferenz-versammelt-digitale-vordenker-in-berlin/index.html
Hey there,<br />This pull requests contains the build changes caused by 7375096f20c7c594420593988583a12b1d16a9f8.<br/>When you merge this the changes will be deployed to production on [sinnerschrader.com](https://sinnerschrader.com).<br/>Cheers<br/>---<br />**Target**: Production :rotating_light:<br />**Source**: Commit to master
> Deploy changes for 7375096

- src/templates/module_18_infographic3/styles.less
Add min-height to container 
Fixes #113
> fix: ensure sufficient container height

- src/templates/module_22_story2/styles.less
Removed position absolute from .mod-story2 .teaser
Added display flex to .mod-story2
Added negative margin-bottom to .mod-story2 .teaser
fixes #203
> fix: prevent teaser from overlapping

- src/templates/module_22_story2/styles.less
Removed a few lines of commented out code
> style: remove commented out code

- src/templates/_layouts/_partials/head.html
> fix: prevent telephone number format detection

- src/pages/index.html
- src/templates/module_01_hero/styles.less
- src/templates/module_01_hero/template.html
> fix: add new hero content position

- src/templates/module_19_quoteimage/styles.less
- src/templates/module_19_quoteimage/template.html
fix #223 
blurry images fixed in #214
> fix(module): overlapping text from quoteimages

- src/templates/module_15_statement/styles.less
> fix(module): remove min-height, add same spacing as module_20_quote

- src/templates/module_20_quote/styles.less
> fix(module): limit module width, change font style

- src/css/app.less
- src/pages/about/why.html
- src/templates/module_18_infographic3/styles.less
- src/templates/module_21_story1/styles.less
- src/templates/module_gradient/styles.less
- src/templates/module_gradient/template.html
add background gradient module
> fix: background gradient

- src/templates/element_card/styles.less
> fix: limit grey background

- src/templates/module_07_locations/styles.less
> fix: limit locationMap width

- .travis.yml
Builds on #244, picks up changes related to Travis control flow.
> chore: mark ci red if deployments fail

- src/pages/about/why.html
- src/templates/module_20_quote/styles.less
- src/templates/module_20_quote/template.html
> feat: add crosslinks to quote module

- .travis.yml
- scripts/deploy-staging.sh
- scripts/deploy.sh
* change cp call to copy contents of docs/ instead of directory itself 
closes #230
> chore: copy contents of docs instead of directory

- src/pages/index.html
- src/templates/module_08_links/template.html
Heya,
HTTPS make the web better for everyone. Please convert the links with this request.
Cheers
Florian
> Convert remaining HTTP links to HTTPS

- src/pages/work/books.html
the old version led to no results on the amazon search
> fix: find desired transformational products book
